apiVersion: v1
kind: ConfigMap
metadata:
  name: observatorium-otelcol-service-ca
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: observatorium-otelcol
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: localhost:55680
            auth:
              oidc:
                issuer_url: https://dex-dex.apps.llc.o4b5.p1.openshiftapps.com/dex
                audience: test
                username_claim: email

    processors:
      # this processor will read an env var named OTEL_RESOURCE (key=value,key2=value2) and add each key-value pair as a resource attribute
      resourcedetection:
        detectors:
          - env

      # this routing table will always route spans to the 'jaeger' exporter
      routing:
        default_exporters:
        - jaeger
        from_attribute: X-Tenant
        table:
        - value: test
          exporters:
          - jaeger

    exporters:
      jaeger:
        endpoint: localhost:14250
        insecure: true

    service:
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            # - authentication
            - resourcedetection
            - routing
          exporters:
            - jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: observatorium-otelcol
  labels:
    app: observatorium-otelcol
spec:
  ports:
  - port: 55680
    targetPort: 55680
  selector:
    app: observatorium-otelcol
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observatorium-otelcol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observatorium-otelcol
  template:
    metadata:
      labels:
        app: observatorium-otelcol
    spec:
      containers:
      - name: otelcol
        image: quay.io/observatorium/opentelemetry-collector:0.3.0
        args: ["--config=/etc/otelcol/config.yaml"]
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
        ports:
        - containerPort: 55680
        volumeMounts:
        - name: otelcol-config
          mountPath: /etc/otelcol
        - name: service-ca
          mountPath: /etc/pki/ca-trust/source/anchors
      volumes:
        - name: otelcol-config
          configMap:
            name: observatorium-otelcol
        - name: service-ca
          configMap:
            name: observatorium-otelcol-service-ca
